# Discussion {#discussion}

This report introduces high resolution mapping based on Bayesian geospatial techniques implemented in the open source statistical computing environment R [@R2018]. The core of the modelling method is implemented in the R package `INLA` [@INLA_theory_1;@INLA_theory_2;@INLA_R_1;@INLA_R_2]. The emphasis is on providing and explaining the R codes required to go from the *raw* data to the final maps.

Three development indicators are mapped for El Salvador: median income, adult literacy and poverty. The data on these development indicators come from the *Encuesta de Hogares de Propositos Multiples* (EHPM), an annual survey conducted in 1664 *segmentos* among 20,645 household in 2017. A suite of more than 20 remote sensing and geographic information system open source data are used to derive a list of 86 potential predictors, hereafter covariates. After having standardized the covariates, we apply an unsupervised dimension reduction process to reduce this number to 50. This limits the effect of multicollinearity in subsequent modelling and limits the risk of retaining covariates because of chance correlation in the subsequent covariates selection. Next, we apply a backward stepwise covariates selection process in order to select a parsimonious model specification. We tested several likelihood function (*Gaussian*, *Gamma* and *Beta*) and spatial dependence structure (SPDE or the BYM 2 models).

The best results are obtained with the SPDE approach and, at the *segmento* level, yields a $R^2$ on the final test set of 50% for income, 43% for illiteracy and only 23% for poverty. Once the results are aggregated at the *municipio* level, the $R^2$ increases to 84% for income, 80% for literacy and 61% for poverty. 

We spent limited time exploring interaction terms and non-linear relationships between covariates and outcome variables. Another avenue for amelioration would be to develop a spatio-temporal model in order to take into account the time dimension. This is made possible as the EHPM is collected annually. A spatio-temporal model would permit to monitor trends in the socio-economic and SDG indicators of interest. Lastly, other modeling architectures such as random forests or convolutional neural networks could take advantage of nonlinear effects, potentially increasing the predictive accuracy of the models.

Another direction for potentially improving the granularity of socio-economic maps lies in the use of mobile phone call-detail records. Covariate data derived from mobile phone call-detail records (CDRs) have been shown to correlate well with poverty indicators both at the household and aggregate level [e.g. @blumenstock2015predicting;@steele2017mapping]. CDRs have the advantage also of being highly granular in both space and time, presenting the possibility to potentially monitor variation in population wellbeing at higher frequency. While the technical demands and requirements to negotiate access to CDR data and conduct meaningful analyses with them is high, there are many potential applications for these data (e.g. mobility analysis, disaster response and preparedness) and the marginal cost of each additional project is low once the agreements and the IT system are in place. 

Lastly, a lot of the data pre-processing work and some of the analytical steps could be packaged and automatised in a software. This could further streamline the process of creating these high resolution maps of development indicators.

These high resolution maps of development indicators may allow more accurate targeting of government interventions aimed at reducing poverty or increasing literacy rates among adults. Secondly, the methods presented here are portable to other socioeconomic and SDG indicators of interest. They could play a key role in monitoring and reporting on SDG achievements. Thirdly, other than the survey *segmento* level survey data, the methods described here are conducted using freely available data sources on freely-available software. Fourth, the method does not rely on the use of census data as do traditional small area estimation methods. It can hence be applied independently of any census round. Fifthly, the methods can be readily deployed by analysts with masters-level statistical training. These five points make the method very suitable for incorporation in routine and standard practices of National Statistical Offices (NSOs).  

A next possible step is to present these methods to NSOs to generate discourse on the value of these methods, potential improvements to increase their operational relevance and implications for their integration into decision-making frameworks. Our hope is that the relative ease of these methods, the open-source nature of the software and covariate data as well as the large number of code examples in this report (and on the web in general) will encourage their adoption by NSOs. Experts from the Flowminder Foundation are available to provide technical training and support to strengthen in-house capacity at NSOs to use these methods. This report could constitute the backbone of a short course of up to five days to equip a first cohort of statisticians with the know-how for using in confidence these methods, data and the R software for high resolution mapping of development indicators. 